services:
  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 54320:5432

volumes:
  postgres-data:
    driver: local
